### PR TITLE
loom and create campaign updates

### PR DESCRIPTION
**Pull request by greenealexander**
## 📸 Screengrabs
| Supported Browser  | Unsupported Browser |
|--|--|
| Screen Shot 2022-11-29 at 21 37 06 | Screen Shot 2022-11-29 at 21 35 45 |

https://user-images.githubusercontent.com/17241472/204702520-7a92cfe8-cd4b-48aa-bd9e-a89bf79eb04a.mov

### CODE REVIEW

**Review by sirgawain0x — CHANGES_REQUESTED** [review]
This came up on chrome and trying to create a campaign.

**Review by sirgawain0x — CHANGES_REQUESTED** [review]
Steps to duplicate:

1. Connect wallet
2. Sign In (as a brand)
3. Click Create Campaign
4. Error

Screenshot 2022-11-30 at 1 03 06 PM

Screenshot 2022-12-01 at 12 44 25 AM

**Comment by greenealexander** [comment]
> Steps to duplicate:
> 
>     1. Connect wallet
> 
>     2. Sign In (as a brand)
> 
>     3. Click Create Campaign
> 
>     4. Error
> 
> 
> Screenshot 2022-11-30 at 1 03 06 PM
> 
> Screenshot 2022-12-01 at 12 44 25 AM

Fixed!

https://user-images.githubusercontent.com/17241472/204980804-b4ca0b2c-9ba9-4ff8-91c1-63c22758fd6c.mov

**Review by sirgawain0x — APPROVED** [review]
Definitely Fixed 🛠️

**Pull request merged**
